### ISSUE TITLE
Scale mount speed with pokemon stats?

### ISSUE THREAD

**Issue by DragonPatalo** [IoIxD/Cobblemounts#25]
Hi, no idea if this is even possible but i think it would be cool if the speed of the pokemon was scaled with their speed stat.
I was kinda disapointed at the running speed of Arcanine on land compared to a regular old swampert in water.
That way an Aerodactyl would be faster than a Dragonite.

**Comment by IoIxD** [comment]
Hi, this is supposed to happen. What does your config look like?

**Comment by DragonPatalo** [comment]
I'm using the config file you gave in the mod description.
I double checked to see if i wasn't going crazy but a max IV/EV Arcanine is just as fast as a 0 IV/EV Snorlax.
I can see that the speed scales with level but that's about it.
Thanks for the quick reply btw

**Comment by IoIxD** [comment]
Revisited this when updating the mod and realized that speed DOES scale with the speed stat as it should (in fact, the level isn't even factored in the calculation). The problem here is that due to the scaling, the Pokemon stop being faster well before the point that a level 100 Snorlax's stats are.
The solution for you is to set your speedCap to 2.0. But I think I'm just gonna implement the log speed cap PR that somebody did.
